//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/SkillCursor/CursorInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CursorInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CursorInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CursorInputActions"",
    ""maps"": [
        {
            ""name"": ""CursorActions"",
            ""id"": ""ab216162-9c77-4997-93be-61362c7a44ba"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""1dde62a3-0148-4b8c-8232-30964683c575"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""9096b6d3-5ce9-4961-91e7-ff4633f3f718"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""a685d0cc-684d-43e3-9aec-80fbfe85fd92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""be2017b7-999c-47c9-bc43-8fd59988695d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""afc1d529-fb54-47a0-bb9b-737ea49f59d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""55c5429d-7037-405e-bcc9-82a3072eecf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""585fc8e9-6919-4cf8-ae59-ab0ae25e5714"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""520b8088-ab04-4ac7-9c69-abef5c69d3ca"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c443734f-d982-4ff9-9ccd-bf32567a0959"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""393fb214-7c0c-4062-b05d-7ff94eb4f307"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf0cb626-9691-4ea8-8508-32622e01c517"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""527947ee-3f88-4d05-accd-d27fe01b9845"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CursorActions
        m_CursorActions = asset.FindActionMap("CursorActions", throwIfNotFound: true);
        m_CursorActions_Confirm = m_CursorActions.FindAction("Confirm", throwIfNotFound: true);
        m_CursorActions_Up = m_CursorActions.FindAction("Up", throwIfNotFound: true);
        m_CursorActions_Down = m_CursorActions.FindAction("Down", throwIfNotFound: true);
        m_CursorActions_Right = m_CursorActions.FindAction("Right", throwIfNotFound: true);
        m_CursorActions_Left = m_CursorActions.FindAction("Left", throwIfNotFound: true);
        m_CursorActions_Undo = m_CursorActions.FindAction("Undo", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CursorActions
    private readonly InputActionMap m_CursorActions;
    private List<ICursorActionsActions> m_CursorActionsActionsCallbackInterfaces = new List<ICursorActionsActions>();
    private readonly InputAction m_CursorActions_Confirm;
    private readonly InputAction m_CursorActions_Up;
    private readonly InputAction m_CursorActions_Down;
    private readonly InputAction m_CursorActions_Right;
    private readonly InputAction m_CursorActions_Left;
    private readonly InputAction m_CursorActions_Undo;
    public struct CursorActionsActions
    {
        private @CursorInputActions m_Wrapper;
        public CursorActionsActions(@CursorInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Confirm => m_Wrapper.m_CursorActions_Confirm;
        public InputAction @Up => m_Wrapper.m_CursorActions_Up;
        public InputAction @Down => m_Wrapper.m_CursorActions_Down;
        public InputAction @Right => m_Wrapper.m_CursorActions_Right;
        public InputAction @Left => m_Wrapper.m_CursorActions_Left;
        public InputAction @Undo => m_Wrapper.m_CursorActions_Undo;
        public InputActionMap Get() { return m_Wrapper.m_CursorActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CursorActionsActions set) { return set.Get(); }
        public void AddCallbacks(ICursorActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_CursorActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CursorActionsActionsCallbackInterfaces.Add(instance);
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Undo.started += instance.OnUndo;
            @Undo.performed += instance.OnUndo;
            @Undo.canceled += instance.OnUndo;
        }

        private void UnregisterCallbacks(ICursorActionsActions instance)
        {
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Undo.started -= instance.OnUndo;
            @Undo.performed -= instance.OnUndo;
            @Undo.canceled -= instance.OnUndo;
        }

        public void RemoveCallbacks(ICursorActionsActions instance)
        {
            if (m_Wrapper.m_CursorActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICursorActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_CursorActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CursorActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CursorActionsActions @CursorActions => new CursorActionsActions(this);
    public interface ICursorActionsActions
    {
        void OnConfirm(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnUndo(InputAction.CallbackContext context);
    }
}
