//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Dev/DevInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DevInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DevInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DevInputActions"",
    ""maps"": [
        {
            ""name"": ""DevActions"",
            ""id"": ""36171386-fccc-46d0-96ee-7eb986dfd3fb"",
            ""actions"": [
                {
                    ""name"": ""OpenDevMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6c0a05bd-429c-444e-a6a9-5e982efa26a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""7b3a651b-7bbe-4a17-9207-05d342d274c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""53d62288-c4cb-4e97-86b1-72f535dfbdc3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f5d349cd-d755-4876-aeb5-779a116a663c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDevMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""287efa4e-d2c2-4a4e-9a8c-15495455b20f"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDevMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""29cd993e-fb82-4f06-9871-02b296b538f3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDevMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DevActions
        m_DevActions = asset.FindActionMap("DevActions", throwIfNotFound: true);
        m_DevActions_OpenDevMenu = m_DevActions.FindAction("OpenDevMenu", throwIfNotFound: true);
        m_DevActions_Select = m_DevActions.FindAction("Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DevActions
    private readonly InputActionMap m_DevActions;
    private List<IDevActionsActions> m_DevActionsActionsCallbackInterfaces = new List<IDevActionsActions>();
    private readonly InputAction m_DevActions_OpenDevMenu;
    private readonly InputAction m_DevActions_Select;
    public struct DevActionsActions
    {
        private @DevInputActions m_Wrapper;
        public DevActionsActions(@DevInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenDevMenu => m_Wrapper.m_DevActions_OpenDevMenu;
        public InputAction @Select => m_Wrapper.m_DevActions_Select;
        public InputActionMap Get() { return m_Wrapper.m_DevActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DevActionsActions set) { return set.Get(); }
        public void AddCallbacks(IDevActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_DevActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DevActionsActionsCallbackInterfaces.Add(instance);
            @OpenDevMenu.started += instance.OnOpenDevMenu;
            @OpenDevMenu.performed += instance.OnOpenDevMenu;
            @OpenDevMenu.canceled += instance.OnOpenDevMenu;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IDevActionsActions instance)
        {
            @OpenDevMenu.started -= instance.OnOpenDevMenu;
            @OpenDevMenu.performed -= instance.OnOpenDevMenu;
            @OpenDevMenu.canceled -= instance.OnOpenDevMenu;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IDevActionsActions instance)
        {
            if (m_Wrapper.m_DevActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDevActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_DevActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DevActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DevActionsActions @DevActions => new DevActionsActions(this);
    public interface IDevActionsActions
    {
        void OnOpenDevMenu(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
}
