//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerActions"",
            ""id"": ""397169a1-1306-49b0-a643-daf866fbf7b0"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""e76aa6e0-ac30-4a54-9305-7dc4b3af5016"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""4815318d-b77a-484e-a042-397136fce20f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""54119730-a978-4c4c-b289-1ca0d1d95ea4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""9a599ce3-a351-45e1-9b91-228a9a4652e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""09d8befd-f832-4aca-a35b-b84b99a52ea0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""34bfd009-30d3-423d-81c9-e1a1e49625e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot0"",
                    ""type"": ""Button"",
                    ""id"": ""47b276b9-e18e-4fcf-980a-2471df195389"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""36c77688-1276-48d4-9e58-a51bcf594ed8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""9cf937dd-2753-4a9f-898d-8d4e125cc224"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""58002a7f-3837-4538-b1d1-27a31d973230"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot4"",
                    ""type"": ""Button"",
                    ""id"": ""66ba7d3a-69f4-41d6-b9ad-0b7d267a5163"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot5"",
                    ""type"": ""Button"",
                    ""id"": ""7d28718f-3fa4-4631-870b-18a6a96c2511"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot6"",
                    ""type"": ""Button"",
                    ""id"": ""c39608fb-4cc6-4d8d-8a86-f91cdffab4d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot7"",
                    ""type"": ""Button"",
                    ""id"": ""c3fd3f97-fc9c-45a1-aa71-118c58a38dd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot8"",
                    ""type"": ""Button"",
                    ""id"": ""67754f7f-d3dc-4dc3-9d52-d2da15815ef2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBarSlot9"",
                    ""type"": ""Button"",
                    ""id"": ""42d17005-cf8c-43cc-8666-f95c73753302"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a412dbe-57c1-4907-aa01-5926e054c54f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a779778-b769-41dc-bc3c-cbf619414c7b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35e1dc9c-c770-40b6-924e-6daed262b038"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f508e02-3e28-41db-b641-91ca70696712"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0130118d-e742-4054-8a70-7e20b41acf1f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cf28365-66ca-43c0-946a-a1d7f97d6352"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94bb5e6b-8449-4e38-9cef-ecbfc5691c12"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""813749af-86a6-4e45-a696-c3006a028e7d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e311c32-ec07-47c7-8ed4-3f17ec4b3bf1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec7a683a-0d51-4476-bd9d-4d6297cf74e5"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e5dbc4a-a58b-40a6-b0dc-6ab93b36e865"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f67c2729-16d0-40ac-865a-e305c73e4ebf"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8a337cb-ccf2-4741-ac48-1c3211356581"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32f8dc11-a866-47bd-9f69-e19261819020"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d43e035f-9dc2-4960-b781-30ecfd2b8631"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecbaa280-3072-4473-b89c-36839e482644"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBarSlot9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActions
        m_PlayerActions = asset.FindActionMap("PlayerActions", throwIfNotFound: true);
        m_PlayerActions_Up = m_PlayerActions.FindAction("Up", throwIfNotFound: true);
        m_PlayerActions_Down = m_PlayerActions.FindAction("Down", throwIfNotFound: true);
        m_PlayerActions_Right = m_PlayerActions.FindAction("Right", throwIfNotFound: true);
        m_PlayerActions_Left = m_PlayerActions.FindAction("Left", throwIfNotFound: true);
        m_PlayerActions_Confirm = m_PlayerActions.FindAction("Confirm", throwIfNotFound: true);
        m_PlayerActions_Cancel = m_PlayerActions.FindAction("Cancel", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot0 = m_PlayerActions.FindAction("HotBarSlot0", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot1 = m_PlayerActions.FindAction("HotBarSlot1", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot2 = m_PlayerActions.FindAction("HotBarSlot2", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot3 = m_PlayerActions.FindAction("HotBarSlot3", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot4 = m_PlayerActions.FindAction("HotBarSlot4", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot5 = m_PlayerActions.FindAction("HotBarSlot5", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot6 = m_PlayerActions.FindAction("HotBarSlot6", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot7 = m_PlayerActions.FindAction("HotBarSlot7", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot8 = m_PlayerActions.FindAction("HotBarSlot8", throwIfNotFound: true);
        m_PlayerActions_HotBarSlot9 = m_PlayerActions.FindAction("HotBarSlot9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActions
    private readonly InputActionMap m_PlayerActions;
    private List<IPlayerActionsActions> m_PlayerActionsActionsCallbackInterfaces = new List<IPlayerActionsActions>();
    private readonly InputAction m_PlayerActions_Up;
    private readonly InputAction m_PlayerActions_Down;
    private readonly InputAction m_PlayerActions_Right;
    private readonly InputAction m_PlayerActions_Left;
    private readonly InputAction m_PlayerActions_Confirm;
    private readonly InputAction m_PlayerActions_Cancel;
    private readonly InputAction m_PlayerActions_HotBarSlot0;
    private readonly InputAction m_PlayerActions_HotBarSlot1;
    private readonly InputAction m_PlayerActions_HotBarSlot2;
    private readonly InputAction m_PlayerActions_HotBarSlot3;
    private readonly InputAction m_PlayerActions_HotBarSlot4;
    private readonly InputAction m_PlayerActions_HotBarSlot5;
    private readonly InputAction m_PlayerActions_HotBarSlot6;
    private readonly InputAction m_PlayerActions_HotBarSlot7;
    private readonly InputAction m_PlayerActions_HotBarSlot8;
    private readonly InputAction m_PlayerActions_HotBarSlot9;
    public struct PlayerActionsActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActionsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_PlayerActions_Up;
        public InputAction @Down => m_Wrapper.m_PlayerActions_Down;
        public InputAction @Right => m_Wrapper.m_PlayerActions_Right;
        public InputAction @Left => m_Wrapper.m_PlayerActions_Left;
        public InputAction @Confirm => m_Wrapper.m_PlayerActions_Confirm;
        public InputAction @Cancel => m_Wrapper.m_PlayerActions_Cancel;
        public InputAction @HotBarSlot0 => m_Wrapper.m_PlayerActions_HotBarSlot0;
        public InputAction @HotBarSlot1 => m_Wrapper.m_PlayerActions_HotBarSlot1;
        public InputAction @HotBarSlot2 => m_Wrapper.m_PlayerActions_HotBarSlot2;
        public InputAction @HotBarSlot3 => m_Wrapper.m_PlayerActions_HotBarSlot3;
        public InputAction @HotBarSlot4 => m_Wrapper.m_PlayerActions_HotBarSlot4;
        public InputAction @HotBarSlot5 => m_Wrapper.m_PlayerActions_HotBarSlot5;
        public InputAction @HotBarSlot6 => m_Wrapper.m_PlayerActions_HotBarSlot6;
        public InputAction @HotBarSlot7 => m_Wrapper.m_PlayerActions_HotBarSlot7;
        public InputAction @HotBarSlot8 => m_Wrapper.m_PlayerActions_HotBarSlot8;
        public InputAction @HotBarSlot9 => m_Wrapper.m_PlayerActions_HotBarSlot9;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Add(instance);
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @HotBarSlot0.started += instance.OnHotBarSlot0;
            @HotBarSlot0.performed += instance.OnHotBarSlot0;
            @HotBarSlot0.canceled += instance.OnHotBarSlot0;
            @HotBarSlot1.started += instance.OnHotBarSlot1;
            @HotBarSlot1.performed += instance.OnHotBarSlot1;
            @HotBarSlot1.canceled += instance.OnHotBarSlot1;
            @HotBarSlot2.started += instance.OnHotBarSlot2;
            @HotBarSlot2.performed += instance.OnHotBarSlot2;
            @HotBarSlot2.canceled += instance.OnHotBarSlot2;
            @HotBarSlot3.started += instance.OnHotBarSlot3;
            @HotBarSlot3.performed += instance.OnHotBarSlot3;
            @HotBarSlot3.canceled += instance.OnHotBarSlot3;
            @HotBarSlot4.started += instance.OnHotBarSlot4;
            @HotBarSlot4.performed += instance.OnHotBarSlot4;
            @HotBarSlot4.canceled += instance.OnHotBarSlot4;
            @HotBarSlot5.started += instance.OnHotBarSlot5;
            @HotBarSlot5.performed += instance.OnHotBarSlot5;
            @HotBarSlot5.canceled += instance.OnHotBarSlot5;
            @HotBarSlot6.started += instance.OnHotBarSlot6;
            @HotBarSlot6.performed += instance.OnHotBarSlot6;
            @HotBarSlot6.canceled += instance.OnHotBarSlot6;
            @HotBarSlot7.started += instance.OnHotBarSlot7;
            @HotBarSlot7.performed += instance.OnHotBarSlot7;
            @HotBarSlot7.canceled += instance.OnHotBarSlot7;
            @HotBarSlot8.started += instance.OnHotBarSlot8;
            @HotBarSlot8.performed += instance.OnHotBarSlot8;
            @HotBarSlot8.canceled += instance.OnHotBarSlot8;
            @HotBarSlot9.started += instance.OnHotBarSlot9;
            @HotBarSlot9.performed += instance.OnHotBarSlot9;
            @HotBarSlot9.canceled += instance.OnHotBarSlot9;
        }

        private void UnregisterCallbacks(IPlayerActionsActions instance)
        {
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @HotBarSlot0.started -= instance.OnHotBarSlot0;
            @HotBarSlot0.performed -= instance.OnHotBarSlot0;
            @HotBarSlot0.canceled -= instance.OnHotBarSlot0;
            @HotBarSlot1.started -= instance.OnHotBarSlot1;
            @HotBarSlot1.performed -= instance.OnHotBarSlot1;
            @HotBarSlot1.canceled -= instance.OnHotBarSlot1;
            @HotBarSlot2.started -= instance.OnHotBarSlot2;
            @HotBarSlot2.performed -= instance.OnHotBarSlot2;
            @HotBarSlot2.canceled -= instance.OnHotBarSlot2;
            @HotBarSlot3.started -= instance.OnHotBarSlot3;
            @HotBarSlot3.performed -= instance.OnHotBarSlot3;
            @HotBarSlot3.canceled -= instance.OnHotBarSlot3;
            @HotBarSlot4.started -= instance.OnHotBarSlot4;
            @HotBarSlot4.performed -= instance.OnHotBarSlot4;
            @HotBarSlot4.canceled -= instance.OnHotBarSlot4;
            @HotBarSlot5.started -= instance.OnHotBarSlot5;
            @HotBarSlot5.performed -= instance.OnHotBarSlot5;
            @HotBarSlot5.canceled -= instance.OnHotBarSlot5;
            @HotBarSlot6.started -= instance.OnHotBarSlot6;
            @HotBarSlot6.performed -= instance.OnHotBarSlot6;
            @HotBarSlot6.canceled -= instance.OnHotBarSlot6;
            @HotBarSlot7.started -= instance.OnHotBarSlot7;
            @HotBarSlot7.performed -= instance.OnHotBarSlot7;
            @HotBarSlot7.canceled -= instance.OnHotBarSlot7;
            @HotBarSlot8.started -= instance.OnHotBarSlot8;
            @HotBarSlot8.performed -= instance.OnHotBarSlot8;
            @HotBarSlot8.canceled -= instance.OnHotBarSlot8;
            @HotBarSlot9.started -= instance.OnHotBarSlot9;
            @HotBarSlot9.performed -= instance.OnHotBarSlot9;
            @HotBarSlot9.canceled -= instance.OnHotBarSlot9;
        }

        public void RemoveCallbacks(IPlayerActionsActions instance)
        {
            if (m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionsActions @PlayerActions => new PlayerActionsActions(this);
    public interface IPlayerActionsActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnHotBarSlot0(InputAction.CallbackContext context);
        void OnHotBarSlot1(InputAction.CallbackContext context);
        void OnHotBarSlot2(InputAction.CallbackContext context);
        void OnHotBarSlot3(InputAction.CallbackContext context);
        void OnHotBarSlot4(InputAction.CallbackContext context);
        void OnHotBarSlot5(InputAction.CallbackContext context);
        void OnHotBarSlot6(InputAction.CallbackContext context);
        void OnHotBarSlot7(InputAction.CallbackContext context);
        void OnHotBarSlot8(InputAction.CallbackContext context);
        void OnHotBarSlot9(InputAction.CallbackContext context);
    }
}
